name = "v35-site-factory"
compatibility_date = "2024-10-01"
main = "index.js"
account_id = "fe4415f3f3f3b64f651166d1a7ffe1a0"

[[kv_namespaces]]
binding = "KV"
id = "e2eca9fb88584dbca9c59626f28714b6"
