name = "v35-sentinelle"
compatibility_date = "2024-10-01"
main = "index.js"
account_id = "fe4415f3f3f3b64f651166d1a7ffe1a0"

[[kv_namespaces]]
binding = "KV"
id = "e2eca9fb88584dbca9c59626f28714b6"

[[kv_namespaces]]
binding = "LOGS"
id = "83cccd6b37d04c4881063d74d8d263a5"

[triggers]
crons = ["*/5 * * * *"]
